# -*- coding: utf-8 -*-
"""Probability(2)(week10).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZWEcfqoeMaD4sSm_gvuo4fEBvga-pbJ
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

np.random.seed(42)
print('Setup complete. NumPy', np.__version__)

"""**LAB EXERCISE 1 — Probability by Simulation**"""

flips = np.random.randint(0, 2, size=(100_000, 2))
heads = flips.sum(axis=1)

# 1. P(both heads)
p_both_heads = (heads == 2).mean()
print("P(both heads) =", round(p_both_heads, 3))

# 2. P(at least one head)
p_at_least_one = (heads >= 1).mean()
print("P(at least one head) =", round(p_at_least_one, 3))

# 3. P(0) + P(1) + P(2)
p_0 = (heads == 0).mean()
p_1 = (heads == 1).mean()
p_2 = (heads == 2).mean()

print("P(0 heads) =", round(p_0, 3))
print("P(1 head) =", round(p_1, 3))
print("P(2 heads) =", round(p_2, 3))
print("Sum =", round(p_0 + p_1 + p_2, 3))

"""**LAB EXERCISE 2 — Conditional Probability**"""

rolls = np.random.randint(1, 7, size=100_000)

# 1. P(odd | roll < 4)
condition = rolls < 4
p_odd_given_less4 = (rolls[condition] % 2 == 1).mean()
print("P(odd | roll < 4) =", round(p_odd_given_less4, 3))

# 2. P(roll < 4)
p_less4 = (rolls < 4).mean()
print("P(roll < 4) =", round(p_less4, 3))

# 3. P(odd) overall
p_odd = (rolls % 2 == 1).mean()
print("P(odd) =", round(p_odd, 3))

# Check independence
print("Independent?", np.isclose(p_odd_given_less4, p_odd, atol=0.02))

"""**LAB EXERCISE 3 — Bayes Theorem**"""

# 1. Priors / likelihoods
p_spam = 0.20
p_free_given_spam = 0.60
p_free_given_ham = 0.05

# 2. P("free") using total probability
p_free = (p_free_given_spam * p_spam) + \
         (p_free_given_ham * (1 - p_spam))
print("P('free') =", round(p_free, 3))

# 3. Bayes theorem
p_spam_given_free = (p_free_given_spam * p_spam) / p_free
print("P(spam | 'free') =", round(p_spam_given_free, 3))

"""**LAB EXERCISE 4 - Probability Distributions**"""

# 1. Poisson(mu=2) samples + mean
pois = stats.poisson(mu=2).rvs(size=10_000)

print("Poisson sample mean =", round(pois.mean(), 3))

# 2. Histogram
plt.figure(figsize=(7, 4))
plt.hist(pois, bins=range(0, 10), edgecolor='black')
plt.title("Poisson Distribution (mu = 2)")
plt.xlabel("Number of Events")
plt.ylabel("Frequency")
plt.show()

# 3. Gaussian PDF for two sigmas
x = np.linspace(-5, 5, 200)
plt.figure(figsize=(7, 4))
for sigma in [0.5, 2.0]:
    plt.plot(
        x,
        stats.norm(0, sigma).pdf(x),
        label=f"sigma = {sigma}"
    )

plt.title("Gaussian PDF for Different Sigma Values")
plt.xlabel("x")
plt.ylabel("Probability Density")
plt.legend()
plt.show()

"""**LAB EXERCISE 5 - Entropy, KL Divergence & Mutual Information**"""

from scipy.stats import entropy
from sklearn.feature_selection import mutual_info_classif
from sklearn.datasets import load_iris

# 1. Entropy of fair 4-sided and 6-sided dice
die4 = [1/4] * 4
die6 = [1/6] * 6
entropy4 = entropy(die4, base=2)
entropy6 = entropy(die6, base=2)
print("Entropy of fair 4-sided die =", round(entropy4, 3), "bits")
print("Entropy of fair 6-sided die =", round(entropy6, 3), "bits")
if entropy6 > entropy4:
    print("The 6-sided die is more uncertain.")

# 2. KL divergence D(P || Q)
P = np.array([0.7, 0.3])
Q = np.array([0.5, 0.5])
kl = entropy(P, Q, base=2)
print("KL divergence D(P || Q) =", round(kl, 3), "bits")

# 3. Most / least informative iris feature
iris = load_iris()
mi = mutual_info_classif(
    iris.data,
    iris.target,
    random_state=0
)
features = list(zip(iris.feature_names, mi))
features.sort(key=lambda x: x[1], reverse=True)
print("\nMutual Information Scores:")
for name, score in features:
    print(name, ":", round(score, 3))
print("\nMost informative feature:", features[0][0])
print("Least informative feature:", features[-1][0])